Source = \
	SodirFacility.java \
	SodirFixedFacility.java \
	SodirFixedFacilityReader.java \
	SodirMoveableFacility.java \
	SodirMoveableFacilityReader.java \

Main = SodirMoveableFacilityReader

include $(DEV_HOME)/sodir/Makefile

