Source = \
	SodirDevelopmentWellbore.java \
	SodirDevelopmentWellboreReader.java \
	SodirExplorationWellbore.java \
	SodirExplorationWellboreReader.java \
	SodirOtherWellbore.java \
	SodirOtherWellboreReader.java \
	SodirWellbore.java \

Main = SodirDevelopmentWellboreReader

include $(DEV_HOME)/sodir-io/Makefile
