Source = \
	NpdDevelopmentWellbore.java \
	NpdDevelopmentWellboreReader.java \
	NpdExplorationWellbore.java \
	NpdExplorationWellboreReader.java \
	NpdOtherWellbore.java \
	NpdOtherWellboreReader.java \
	NpdWellbore.java \

include $(DEV_HOME)/NpdIo/Makefile
